(function(){
'use strict';
const $=id=>document.getElementById(id),core=window.ChargeVoyRecommendations;
let scenario={start:32,target:80,period:'fora_vazio'},records=[],timer,busy=false,pending=false,mode='recommended';const cache=new Map(),pins=L.layerGroup().addTo(map);let requestCount=0;let tariffWindow=0,tariffBudget=4;
try{const saved=JSON.parse(localStorage.getItem('chargevoy-android-scenario')||'null');if(saved&&core.energyFor({battery_capacity_kwh:60},Number(saved.start),Number(saved.target))!==null)scenario={start:Number(saved.start),target:Number(saved.target),period:saved.period==='vazio'?'vazio':'fora_vazio'};}catch{}
const euro=v=>new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(v);
function summary(){window.AndroidChargeVoy?.syncVehicle?.();const values=selectedValues('.connector-filter');$('android-filter-summary').textContent=[selectedPower==='all'?'':selectedPower+' kW',...values].filter(Boolean).join(' · ')||'Personalizar pesquisa';$('android-vehicle-label').textContent=currentVehicle?[currentVehicle.make,currentVehicle.model].filter(Boolean).join(' '):'Adicionar veículo';$('android-soc-label').textContent=`${scenario.start}% → ${scenario.target}%`;}
function compatibleConnectors(s){let types=currentVehicle?.connector_types||[];if(typeof types==='string'){try{types=JSON.parse(types);}catch{types=[]}}const vehicleTypes=new Set(types.map(connectorCategory));const filters=selectedValues('.connector-filter').filter(x=>x!=='Tesla');return stationConnectorRows(s).filter(c=>(!vehicleTypes.size||vehicleTypes.has(connectorCategory(c.type)))&&(!filters.length||filters.includes(connectorCategory(c.type))));}
function effectivePower(c){const ac=['Type 2','Type 1','Schuko'].includes(connectorCategory(c.type||c.connector_type));const vehicle=Number(ac?currentVehicle?.max_ac_power_kw:currentVehicle?.max_dc_power_kw);return Math.min(Number(c.power_kw)||0,vehicle>0?vehicle:0);}
function baseRows(){if(!currentVehicle||!searchPosition)return[];return records.filter(s=>stationCompatibleWithVehicle(s)).map(s=>{const connectors=compatibleConnectors(s),power=Math.max(0,...connectors.map(effectivePower)),availability=stationAvailability(connectors),energy=core.energyFor(currentVehicle,scenario.start,scenario.target);return{id:s.id,station:s,power,energy,distance:distanceKm(searchPosition,{lat:s.latitude,lon:s.longitude}),minutes:energy&&power?Math.max(5,Math.ceil(energy/power*60/.75)):null,live:availability.kind==='live'&&availability.complete,available:availability.available||0,availability,total:null,card:null};}).filter(s=>s.power>0&&s.distance<=75).sort((a,b)=>a.distance-b.distance||String(a.id).localeCompare(String(b.id))).slice(0,8);}
async function tariffs(id){const old=cache.get(id);if(old&&old.until>Date.now())return old.rows;requestCount++;const rows=await getD1Rows('official_opc_tariffs',`select=station_id,connector_uid,voltage_level,tariff_period,connector_type,power_kw,activation_fee_eur,energy_price_eur_kwh,time_price_eur_min,updated_at&station_id=eq.${encodeURIComponent(id)}&tariff_period=eq.REGULAR&limit=100`).catch(()=>[]);cache.set(id,{rows,until:Date.now()+(rows.length?30*60000:5*60000)});if(cache.size>100)cache.delete(cache.keys().next().value);return rows;}
function priced(row){const members=row.station._location_members||[row.station];const options=[];for(const member of members){const tariffs=cache.get(member.id)?.rows||[];for(const opc of tariffs){const observed=Date.parse(opc.updated_at||'');if(!Number.isFinite(observed)||observed>Date.now()+300000||observed<Date.now()-48*3600000)continue;const compatible=compatibleConnectors(row.station).some(c=>connectorCategory(c.type)===connectorCategory(opc.connector_type));if(!compatible)continue;for(const card of cemeCards.filter(c=>c.estimate_enabled!==false&&!c.subscription_required&&cardIsActive(c))){const price=calculateCardPrice(card,opc,{energyKwh:row.energy},scenario.period,member);if(price&&Number.isFinite(price.total)&&price.total>=0)options.push(price);}}}options.sort((a,b)=>a.total-b.total);const best=options[0];return best?{...row,total:best.total,card:best.card,minutes:best.minutes,price:best}:row;}
function openStation(row,mapOnly=false){if(!row)return;const s=row.station;map.setView([s.latitude,s.longitude],15,{animate:true});if(mapOnly){closeStationPanel();$('map-section').scrollIntoView({behavior:'smooth',block:'start'});}else{document.getElementById('from').value=scenario.start;document.getElementById('to').value=scenario.target;document.getElementById('price-period').value=scenario.period;simMode='energy';selectStation(s,operatorMap.get(s.operator_id));renderSimulator();}}
function view(rows){summary();const result=core.choices(rows);const hero=result[mode]||result.recommended;let text='';if(!currentVehicle)text='Seleciona o veículo para encontrar opções compatíveis.';else if(!searchPosition)text='Permite a localização ou pesquisa uma zona para encontrar opções próximas.';else if(!rows.length)text='Não existem opções compatíveis nesta zona com os filtros atuais.';else if(!hero)text='Ainda não há preço validado e disponibilidade recente suficientes para recomendar. Explora as alternativas abaixo.';
if(text){$('android-hero').innerHTML=`<span class="android-badge">ENCONTRE A SUA OPÇÃO</span><h2>${escapeHtml(text)}</h2><p>Os filtros, o mapa e os detalhes dos postos continuam disponíveis.</p>`;}else{const labels={recommended:'★ RECOMENDADO PARA SI',cheap:'€ MAIS BARATO COM PREÇO VALIDADO',fast:'ϟ MENOR TEMPO ESTIMADO',near:'⌖ MAIS PRÓXIMO'};const total=hero.total===null?'Preço por confirmar':`~${euro(hero.total)}`;const reason=mode==='recommended'?'Equilíbrio entre distância, custo e tempo, com disponibilidade recente.':mode==='cheap'?'Comparação apenas entre os candidatos com tarifa validada.':mode==='fast'?'Tempo de carga estimado com a potência compatível do veículo.':'Distância em linha reta à localização selecionada.';$('android-hero').innerHTML=`<span class="android-badge">${labels[mode]||labels.recommended}</span><h2>${escapeHtml(hero.station.name||operatorMap.get(hero.station.operator_id)||'Posto')}</h2><div class="android-metrics"><span>⌖ ${hero.distance.toFixed(1).replace('.',',')} km</span><span class="${hero.live?'android-good':''}">${escapeHtml(hero.availability.label)}</span><span>ϟ ${hero.power} kW com o veículo</span><span>💰 ${escapeHtml(total)}</span><span>◷ ${hero.minutes?'~'+hero.minutes+' min de carga':'Tempo por confirmar'}</span><span>🔋 Até ${scenario.target}%</span></div><p class="android-reason">ⓘ ${escapeHtml(reason)}</p>${hero.card?`<p>${escapeHtml(hero.card.name)} · ${hero.energy.toFixed(1)} kWh · ${cardSourceLink(hero.card)}</p>`:''}<div class="android-actions"><button id="android-go">IR PARA O POSTO →</button><button id="android-show-map">Ver no mapa</button></div>`;$('android-go').onclick=()=>{openStation(hero);openSelectedStationMaps();};$('android-show-map').onclick=()=>openStation(hero,true);}
$('android-alternatives').innerHTML=[['cheap','€ Mais barato'],['fast','ϟ Mais rápido'],['near','⌖ Mais próximo']].map(([key,label])=>{const r=result[key];return`<button class="android-alternative" data-choice="${key}" ${r?'':'disabled'}><b>${label}</b><strong>${r?escapeHtml(operatorMap.get(r.station.operator_id)||r.station.name||'Posto'):'Sem dados'}</strong><small>${r?r.distance.toFixed(1).replace('.',',')+' km':'Sem opção validada'}<br>${r&&r.total!==null?'~'+euro(r.total):'Preço por confirmar'}${r?.minutes?' · ~'+r.minutes+' min':''}</small></button>`}).join('');$('android-alternatives').querySelectorAll('button').forEach(b=>b.onclick=()=>{mode=b.dataset.choice;view(rows)});
$('android-note').textContent=currentVehicle&&rows.length?`Distâncias em linha reta. Tempos de carga estimados, sem deslocação ou espera. Preços validados em ${result.pricedCount}/${result.totalCount} candidatos; planos com mensalidade excluídos.`:'';
if(rows.length){$('station-cards').innerHTML=rows.filter(r=>r.id!==hero?.id).slice(0,5).map(r=>`<article class="android-station"><h3>${escapeHtml(r.station.name||operatorMap.get(r.station.operator_id)||'Posto')}</h3><div class="android-metrics"><span>⌖ ${r.distance.toFixed(1).replace('.',',')} km</span><span class="${r.live?'android-good':''}">${escapeHtml(r.availability.label)}</span><span>ϟ ${r.power} kW com o veículo</span><span>${r.total!==null?'~'+euro(r.total):'Preço por confirmar'}</span></div><div class="android-station-actions"><button data-android-map="${escapeHtml(r.id)}">Ver no mapa</button><button data-android-details="${escapeHtml(r.id)}">Detalhes e navegar ›</button></div></article>`).join('')||'<p class="android-note">Não existem outros candidatos nesta seleção.</p>';}
pins.clearLayers();const seen=new Set();for(const [key,mark] of [['recommended','★'],['cheap','€'],['fast','ϟ']]){const r=result[key];if(!r||seen.has(r.id))continue;seen.add(r.id);L.marker([r.station.latitude,r.station.longitude],{icon:L.divIcon({className:'android-pin '+key,html:`<span><i>${mark}</i></span>`,iconSize:[36,36],iconAnchor:[18,36]}),title:r.station.name,zIndexOffset:1200}).addTo(pins).on('click',()=>{mode=key;view(rows);openStation(r)});}}
async function refresh(){if(busy){pending=true;return}busy=true;pending=false;const rows=baseRows();view(rows.map(priced));try{if(Date.now()-tariffWindow>=60000){tariffWindow=Date.now();tariffBudget=4;}const ids=new Set();for(const row of rows.slice(0,4)){for(const member of row.station._location_members||[row.station]){if(tariffBudget===0)break;if(ids.has(member.id)||!String(member.source).startsWith('nap'))continue;ids.add(member.id);const hit=cache.get(member.id);if(hit&&hit.until>Date.now())continue;tariffBudget--;await tariffs(member.id);}}view(baseRows().map(priced));}finally{busy=false;if(pending){pending=false;clearTimeout(timer);timer=setTimeout(refresh,250);}}}
window.AndroidChargeVoy={update(stations){records=stations;clearTimeout(timer);timer=setTimeout(refresh,300);},metrics(){return{tariffRequests:requestCount,cacheEntries:cache.size,newD1Writes:0}}};
$('android-vehicle').onclick=()=>$('nav-vehicle').click();$('android-soc').onclick=()=>{$('android-start').value=scenario.start;$('android-target').value=scenario.target;$('android-period').value=scenario.period;$('android-scenario-dialog').showModal()};$('android-save-scenario').onclick=()=>{const start=Number($('android-start').value),target=Number($('android-target').value);if(core.energyFor({battery_capacity_kwh:60},start,target)===null){$('android-scenario-error').textContent='Define uma bateria entre 0 e 99% e um objetivo superior, até 100%.';return}scenario={start,target,period:$('android-period').value};try{localStorage.setItem('chargevoy-android-scenario',JSON.stringify(scenario));}catch{}$('android-scenario-error').textContent='';$('android-scenario-dialog').close();mode='recommended';refresh()};$('android-all-filters').onclick=()=>openFilterMenu();document.addEventListener('change',event=>{if(!event.target.closest('.quick-filters,#filter-menu,#android-vehicle-page'))return;clearTimeout(timer);timer=setTimeout(()=>refresh(),400)});const nav=document.querySelector('.top .nav');nav.classList.add('android-bottom-nav');document.body.appendChild(nav);$('station-cards').addEventListener('click',event=>{const details=event.target.closest('[data-android-details]'),mapButton=event.target.closest('[data-android-map]');const id=details?.dataset.androidDetails||mapButton?.dataset.androidMap;if(id)openStation(baseRows().find(r=>r.id===id),Boolean(mapButton));});const account=$('nav-account');account.classList.add('android-profile');document.querySelector('.top').appendChild(account);
const vehiclePage=document.createElement('section');vehiclePage.id='android-vehicle-page';vehiclePage.innerHTML=`<h2>O meu veículo</h2><div id="android-vehicle-host"></div><section class="android-session"><h3>Sessão de carregamento</h3><label>Nível atual da bateria <b id="android-current-value"></b><input id="android-current-range" type="range" min="0" max="99"></label><label>Nível pretendido <b id="android-target-value"></b><input id="android-target-range" type="range" min="1" max="100"></label><div class="android-energy">ϟ Energia estimada <strong id="android-session-energy">—</strong></div><p id="android-vehicle-error" role="alert"></p><button class="primary" id="android-vehicle-save">GUARDAR PREFERÊNCIAS</button><p class="android-note">Guardado neste dispositivo. A potência e o tempo de carregamento são estimativas.</p></section>`;document.querySelector('.main').prepend(vehiclePage);
const vehiclePanel=document.querySelector('#filter-menu .vehicle');$('android-vehicle-host').appendChild(vehiclePanel);
window.AndroidChargeVoy.syncVehicle=()=>{if(!$('android-current-range').matches(':active'))$('android-current-range').value=scenario.start;if(!$('android-target-range').matches(':active'))$('android-target-range').value=scenario.target;updateSession();const label=currentVehicle?[currentVehicle.make,currentVehicle.model].join(' '):'Adicionar veículo';$('android-route-vehicle').textContent='🚗 '+label+' ›';};
function updateSession(){const a=Number($('android-current-range').value),b=Number($('android-target-range').value);$('android-current-value').textContent=a+'%';$('android-target-value').textContent=b+'%';const energy=core.energyFor(currentVehicle,a,b);$('android-session-energy').textContent=energy===null?'Defina uma sessão válida':energy.toFixed(1).replace('.',',')+' kWh';}
['android-current-range','android-target-range'].forEach(id=>$(id).addEventListener('input',updateSession));
$('android-vehicle-save').onclick=()=>{const start=Number($('android-current-range').value),target=Number($('android-target-range').value);if(core.energyFor(currentVehicle,start,target)===null){$('android-vehicle-error').textContent='O objetivo deve ser superior à bateria atual. Verifique a capacidade do veículo.';return;}scenario={...scenario,start,target};try{localStorage.setItem('chargevoy-android-scenario',JSON.stringify(scenario));}catch{}$('android-vehicle-error').textContent='Preferências guardadas.';mode='recommended';refresh();};
window.AndroidChargeVoy.showVehicle=()=>{closeFilterMenu();vehiclePage.scrollIntoView({block:'start'});summary();};
window.AndroidChargeVoy.pageChanged=page=>{closeModalForNavigation();closeFilterMenu();if(page==='vehicle')window.AndroidChargeVoy.showVehicle();requestAnimationFrame(()=>map.invalidateSize());};
function closeModalForNavigation(){$('app-modal').classList.remove('open');$('app-modal').setAttribute('aria-hidden','true');}
const routeVehicle=document.createElement('button');routeVehicle.id='android-route-vehicle';routeVehicle.className='android-route-vehicle';routeVehicle.onclick=()=>$('nav-vehicle').click();document.querySelector('.routeform').before(routeVehicle);
for(const [id,text] of [['route-battery','Bateria de partida (%)'],['route-reserve','Reserva à chegada (%)']]){const input=$(id),label=document.createElement('label');label.textContent=text;input.before(label);label.appendChild(input);}
document.querySelector('.routehead b').textContent='Planear viagem';$('plan-route').textContent='➤ PLANEAR ROTA';
$('android-note').before(Object.assign(document.createElement('details'),{className:'android-estimate-info',innerHTML:'<summary>Sobre estas estimativas ⓘ</summary>'}));document.querySelector('.android-estimate-info').appendChild($('android-note'));
// All screen transitions use the already loaded catalogue; no database reads or writes.
document.body.dataset.androidPage='map';
if(window.Capacitor?.isNativePlatform?.())window.Capacitor.Plugins?.App?.addListener('backButton',()=>{if($('android-scenario-dialog').open){$('android-scenario-dialog').close();return;}if($('app-modal').classList.contains('open')){closeModal();return;}if(document.body.dataset.androidPage!=='map'||selectedStation){$('nav-map').click();return;}if($('filter-menu').classList.contains('mobile-open')){closeFilterMenu();return;}window.Capacitor.Plugins.App.exitApp();});
summary();renderStations(false);
})();
