name = "broken-mud-373e"
main = "worker/index.js"
compatibility_date = "2026-09-25"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "CHARGEVOY_DB"
database_name = "chargevoy-fallback"
# database_id = "ID_DA_BASE_D1"

[[kv_namespaces]]
binding = "AVAILABILITY_KV"
id = "KV_NAMESPACE_ID_PLACEHOLDER"

