import {cp,readFile,writeFile,mkdir,rm} from 'node:fs/promises';
import {resolve} from 'node:path';
const app=resolve(import.meta.dirname),web=resolve(app,'../../ev-charge-portugal-github-ready'),dist=resolve(app,'dist');
await rm(dist,{recursive:true,force:true});await mkdir(dist,{recursive:true});
await cp(resolve(web,'assets'),resolve(dist,'assets'),{recursive:true});
await cp(resolve(web,'icon.svg'),resolve(dist,'icon.svg'));
await cp(resolve(app,'src/index.html'),resolve(dist,'index.html'));
for(const name of ['chargevoy.js','android-ui.js','android-ui.css','recommendations.js'])await cp(resolve(app,'src',name),resolve(dist,'assets',name));
await writeFile(resolve(dist,'android-build.json'),JSON.stringify({interface:'android-only',version:'1.1.0',built_at:new Date().toISOString()}));
console.log('Android-only bundle built in apps/chargevoy-android/dist; web bundle untouched.');
