import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import vm from 'node:vm';
const ctx=vm.createContext({});vm.runInContext(await readFile(new URL('./src/recommendations.js',import.meta.url),'utf8'),ctx);const {energyFor,choices}=ctx.ChargeVoyRecommendations;
const row=(id,extra={})=>({id,distance:2,power:100,energy:28.8,minutes:20,total:9,live:true,available:2,...extra});
test('energy uses selected battery and SOC without fabricated capacity',()=>{assert.equal(energyFor({battery_capacity_kwh:60},32,80),28.8);assert.equal(energyFor(null,32,80),null);for(const [a,b]of [[80,32],[-1,80],[32,101],[32,32],[NaN,80]])assert.equal(energyFor({battery_capacity_kwh:60},a,b),null)});
test('recommended requires price, fresh availability and valid time',()=>{for(const extra of [{live:false},{available:0},{total:null},{minutes:null},{energy:null},{distance:76},{power:0}])assert.equal(choices([row('a',extra)]).recommended,null);assert.equal(choices([row('a')]).recommended.id,'a')});
test('alternatives can differ and cheapest never treats missing price as zero',()=>{const c=choices([row('cheap',{total:5,minutes:30,distance:4}),row('fast',{total:12,minutes:10,distance:3}),row('near',{total:null,minutes:40,distance:.3})]);assert.equal(c.cheap.id,'cheap');assert.equal(c.fast.id,'fast');assert.equal(c.near.id,'near');assert.equal(c.pricedCount,2)});
test('empty and incompatible/outside candidates give no recommendation',()=>{const c=choices([row('a',{power:0}),row('b',{distance:100})]);assert.equal(c.totalCount,0);assert.equal(c.recommended,null);assert.equal(c.near,null)});

test('Android price calculation uses each candidate network rather than the open station',async()=>{
 const web=await readFile(new URL('./src/chargevoy.js',import.meta.url),'utf8');const cards=JSON.parse(await readFile(new URL('../../ev-charge-portugal-github-ready/assets/ceme-cards.json',import.meta.url),'utf8'));
 class PricingDate extends Date{constructor(...args){super(...(args.length?args:['2026-10-03T12:00:00Z']))}}
 const ctx=vm.createContext({Date:PricingDate,currentVehicle:{max_dc_power_kw:100},operatorMap:new Map([['atlante','Atlante'],['other','Other']]),selectedStation:{operator_id:'atlante'}});
 const extract=(a,b)=>web.slice(web.indexOf(a),web.indexOf(b,web.indexOf(a)));
 vm.runInContext(extract('function cardEnergyRate(','function cardSourceLink('),ctx);vm.runInContext(extract('function calculateCardPrice(','function adHocPriceMarkup('),ctx);
 const card=cards.find(x=>x.id==='myatlante'),opc={connector_type:'CCS',power_kw:50};const other=ctx.calculateCardPrice(card,opc,{energyKwh:20},'fora_vazio',{operator_id:'other'}),own=ctx.calculateCardPrice(card,opc,{energyKwh:20},'fora_vazio',{operator_id:'atlante'});
 assert.equal(other.total,11);assert.equal(own.total,11);assert.equal(other.cashback,1.1);assert.equal(own.cashback,2.75);assert.equal(ctx.calculateCardPrice(card,{connector_type:'Type 2',power_kw:50},{energyKwh:20},'fora_vazio',{operator_id:'other'}),null);
});

test('a priced alternative remains useful with unknown live availability, without being a live recommendation',()=>{const x=choices([row('known-price',{live:false,available:0})]);assert.equal(x.recommended,null);assert.equal(x.suggested.id,'known-price');assert.equal(choices([row('full',{live:true,available:0})]).suggested,null)});
test('fast alternative uses the faster connector, with its matching cost',()=>{const x=choices([row('multi',{minutes:120,total:5,fastChoice:row('multi',{minutes:10,total:12,power:150})}),row('other',{minutes:20,total:8})]);assert.equal(x.cheap.total,5);assert.equal(x.fast.id,'multi');assert.equal(x.fast.minutes,10);assert.equal(x.fast.total,12)});
test('vehicle photo selection respects generation ranges',async()=>{const source=await readFile(new URL('./src/chargevoy.js',import.meta.url),'utf8');const ctx=vm.createContext({vehiclePhotoCatalog:new Map([['tesla|model y',[{min_year:2020,max_year:2024,image:'old'},{min_year:2025,max_year:null,image:'new'}]]])});vm.runInContext(source.slice(source.indexOf('function vehiclePhotoFor('),source.indexOf('function renderVehicleImage(')),ctx);assert.equal(ctx.vehiclePhotoFor({make:'Tesla',model:'Model Y',model_year_start:2023}).image,'old');assert.equal(ctx.vehiclePhotoFor({make:'Tesla',model:'Model Y',model_year_start:2025}).image,'new');});

test('cheapest cost keeps its own occupied connector status instead of borrowing availability',()=>{const x=choices([row('site',{total:12,available:1,cheapChoice:row('site',{total:5,available:0})})]);assert.equal(x.recommended.total,12);assert.equal(x.cheap.total,5);assert.equal(x.cheap.available,0)});
